config/routes.rb
Mixtape::Application.routes.draw do

  resources :users
  resources :sessions, :only  =>[:new, :create, :destroy]  
 
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/signup',:to =>'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'

   root :to => 'pages#home'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  attr_accessor   :password 
  
  
 
  email_regex =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates_presence_of   :name
  validates_length_of     :name,:maximum => 50
  validates_presence_of   :email
  validates_format_of     :email, :with => email_regex
  validates_uniqueness_of :email, :case_sensitive => false
  validates_presence_of    :password
  validates_length_of     :password, :within => 6..50
  validates_confirmation_of :password

  before_save :encrypt_password
  def has_password?(password)
    encrypt(password) == encrypted_password 
  end  


  def self.authenticate(email,password)
     user = User.find_by_email(email)
     return nil if user.nil?|| !user.has_password?(password) 
     return user if user.has_password?(password)
  end
  
  def self.authenticate_with_salt(id, salt)
    user = User.find_by_id(id)
    return nil if user.nil?
    return user if user.salt == salt
  end
  

  private
   
    def encrypt_password
      self.salt = make_salt if new_record? #make salt if the record is new
      self.encrypted_password = encrypt(self.password)
    end
  
    def  encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end
  
  def about
    @title = "About"
  end
   
  def contact
    @title = "Contact"
  end

  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],params[:session][:password])

    if user.nil?
     #render the login page again
      #display error messages

     flash.now[:error] = "Invalid email/password combination"
     @title ="Sign in"
     render 'new'
    else
      #sign in the user and redirect to show/profile page
      sign_in(user)
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only =>[:edit, :update, :destroy]
  before_filter :correct_user, :only =>[:edit,:update]
  before_filter :admin_user, :only =>[:destroy]
  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
   
    if @user.save
       sign_in(@user)
       flash[:success] = "Welcome to our App" 
       redirect_to @user
    else
       @title = "Sign up"
       @user.password.clear
       @user.password_confirmation.clear
       render 'new'
    end
  end

  def show
    @user  = User.find(params[:id])
    @title = @user.name
  end
  
  def index
    @title = "Members"
    @users = User.all  
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit Profile" 
  end
   
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
       flash[:success] = "Profile updated"
       redirect_to(@user)
    else
      @title ="Edit Profile"
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Successfully Deleted User"
    redirect_to users_path
  end
  private 
    def authenticate
      deny_access unless signed_in?
    end
    def correct_user 
      @user = User.find(params[:id])
      redirect_to root_path unless @user == current_user
    end
    def admin_user
      if(current_user.admin == false)
        flash[:error] = "Not Authorized"
        redirect_to root_path
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.signed.permanent[:remember_token] =[user.id, user.salt]   
    current_user = user
  end

  def signed_in?
   !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user||= user_from_token
  end

  def sign_out
  cookies.delete(:remember_token)
  current_user = nil  
 end
  private 
    def user_from_token
      User.authenticate_with_salt(*remember_token)
    end

  
    def remember_token
      cookies.signed[:remember_token] ||[nil,nil]
    end
    def deny_access
      flash[:warning] = "Please Sign in to access page"
      redirect_to signin_path
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
<head>  
 <title>Mixtape|<%=@title%></title>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
 <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }
      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }

    </style>
 
</head>
<body>
   
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Mixtape</a>
          <ul class="nav">
            <li class="active"><%=link_to("Home",root_path)%></a></li>
            <li><a href="#music">Music</a></li>
            <li><%= link_to("Members", users_path)%></li>
          </ul>
    <!---Right nav-->
       <ul class="nav" class="pull-right">
          <% if signed_in? %>
            <li><%=link_to("Profile",user_path(current_user))%></li>
            <li><%=link_to("Sign out",signout_path) %></li>
            <%else %>
          <li><%=link_to "Sign up",new_user_path%></li>            
          <li><%=link_to("Sign in", signin_path)%></li>
          <%end%>
        </ul>
     
        </div>
      </div>
    </div>

 <div class="container">

      <div class="content">
        <div class="page-header">
        </div>
        <div class="row">
          <div class="span10">
             <%flash.each do |key,value|  %>
              <div class ="alert-message <%= key %>"><%=value%></div>
                 <%end%>
              <%=yield%>
              </div>
        
        </div>
      </div>

      <footer>
        <p>&copy; Mixtape 2011</p>
          <ul class="nav">
           <li><%=link_to("About",about_path)%><li>
           <li><%=link_to("Contact",contact_path)%></li>
           <li><%=link_to("Help",help_path)%></li>
        </ul>
      </footer>

    </div> <!-- /container -->

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/help.html.erb
<h1>Help</h1>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%=form_for(@user) do |f|  %>
 <% if @user.errors.any? %>
   <div class ="alert-message error">
     Something's wrong:<br/> 
   <%@user.errors.full_messages.each do |msg| %>
           <%=msg %> <br/>
    <%end%>
   </div>
 <%end%>
   <fieldset>
    <div class = "clearfix">
         <%=f.label :name %>
         <div class ="input"> 
         <%=f.text_field :name %>
         </div>
    </div>
    <div class = "clearfix">
       <%=f.label :email %>
       <div class = "input" >
      <%=f.text_field :email %>
       </div>
    </div> 
   
   <div class = "clearfix">
      <%=f.label :password %> 
      <div class = "input">
      <%=f.password_field :password %>
      </div>
  </div>

  <div class = "clearfix">
     <%= f.label :password_confirmation, "Confirmation" %>
     <div class = "input" >
      <%=f.password_field :password_confirmation%>
     </div>
  
  </div>
 <div class = "clearfix" >
   <%=f.submit :update, :class => "btn primary" %>
 </div>
 </fieldset>


<%end%>

app/views/users/index.html.erb
 <ul>
<% @users.each do |user| %>
  <li><%= user.name %></li> 
  <% if !current_user.nil? && current_user.admin? %>
      <%=link_to"Delete",user, :method => :delete , :confirm => "Are You Sure?" %>
   <%end%>
<%end%>
</ul>

app/views/users/new.html.erb
<h1>Sign up </h1>
<%=form_for(@user) do |f| %>
  <% if @user.errors.any? %> 
      <div class ="alert-message error ">  
        Something's wrong:<br/>
         <%@user.errors.full_messages.each do |msg| %>
           <%=msg%> <br/>
         <%end%> 
    </div> 
  <%end%>
<fieldset> 
<div class="clearfix">
 <%=f.label :name%>
<div class ="input">
 <%=f.text_field :name %>
</div>
</div>
<div class ="clearfix">
 <%=f.label :email%>
  <div class ="input">
  <%=f.text_field :email%>
  </div>
</div>

<div class ="clearfix">

 <%=f.label :password%>
  <div class = "input">
 <%=f.password_field :password %> 
  </div>
</div>
<div class ="clearfix">
 <%=f.label :password_confirmation,"Confirmation" %>
  <div class ="input">
 <%=f.password_field :password_confirmation %>
  </div>
</div> 
<div class ="clearfix">
 <%=f.submit "Sign up",:class =>"btn primary" %>
</div>
<%end%>
</fieldset>
Already have an Account?<%=link_to("Sign in",signin_path) %>

app/views/users/show.html.erb
 <div class ="row">
    <div class ="span4">
      <%=gravatar_image_tag @user.email, :alt => @user.name, :class =>'thumbnail',:gravatar =>{:size =>210 }%>
    </div>
    <div class ="span6">
        <h1><%=@user.name %></h1> <br/>
         
    <% if @user == current_user %>
      <%=link_to "Edit Profile", edit_user_path(@user) %>
    <%end%>

    </div>
 </div>